### ISSUE TITLE
Invalid principal in policy

### ISSUE THREAD

**Issue by anuj9196** [MadSkills-io/fullstack-serverless#14]
My `serverless.yml` configuration:

```
plugins:
  - fullstack-serverless
  - serverless-offline

custom:
  namePrefix: ${self:provider.stage}-${self:provider.region}
  fullstack:
    bucketName: serverless-${self:custom.namePrefix}-frontend
    distributionFolder: webapp/dist/webapp
    singlePageApp: true
    clientCommand: npm install && ng build --aot --prod
    clientSrcPath: webapp
```
But on deploying, it gives error

```
Serverless Error ---------------------------------------
 
  An error occurred: WebAppS3BucketPolicy - Invalid principal in policy (Service: Amazon S3; Status Code: 400; Error Code: MalformedPolicy; Request ID: EE986697DF548390; S3 Extended Request ID: 0c648uKWw85q+U9bTsGXoCUzUFT21wpDPFYjkwYw2RPEh1nfq83xXmjtVAuHmoTeGo8uPQOhhzM=).
```

The errors generating are random. 

When there was no `bucketName` in the config, it was giving an error as 
```
Bucket name should not contain uppercase characters
```

Sometimes, it gives
```
client generation failed
```
