### ISSUE TITLE
Do you wan to proceed? (Y/n) in CI/CD

### ISSUE THREAD

**Issue by anuj9196** [MadSkills-io/fullstack-serverless#15]
I'm using **Bitbucket pipeline** to automate the deployment process.

Here is the `serverless.yml` configuration
```
custom:
  fullstack:
    bucketName: serverless-${self:custom.namePrefix}-frontend
    distributionFolder: webapp/dist/webapp
    singlePageApp: true
    clientCommand: npm install && ng build --aot --prod
    clientSrcPath: webapp
```

The frontend is in **Angular** is installed in the pipeline.

There is a step after building the source that asks to proceed with the changes
```
Do you want to proceed? (Y/n)
```
In the pipeline, it gives the following output and exits without deployment info like endpoints and webapp URL

```
Serverless: Client generation process succeeded...
Serverless: This deployment will:
Serverless: - Remove all existing files from bucket 'qcg-scanning-qa-serverless-qa-us-west-2-frontend'
Serverless: - Upload all files from 'webapp/dist/webapp' to bucket 'qcg-scanning-qa-serverless-qa-us-west-2-frontend'
/bin/sh: tput: not found
?
 
D
o
 
y
o
u
 
w
a
n
t
 
t
o
 
p
r
o
c
e
e
d
?
 
(
Y
/
n
)
 
2019-09-14T11:22:34.853107054Z stdout P 
```

How can I proceed automatically?
