### ISSUE TITLE
Bucket name should not contain uppercase characters

### ISSUE THREAD

**Issue by anuj9196** [MadSkills-io/fullstack-serverless#20]
Here is the my configuration

```
custom:
  variables:
    stage: ${env:DEPLOYMENT_STAGE, 'dev'}
    region: ${env:AWS_REGION, 'us-west-2'}
    memorySize: ${env:MEMORY_SIZE, '512'}
    timeout: ${env:TIMEOUT, '30'}
    deploymentPrefix: ${env:DEPLOYMENT_PREFIX, 'serverless'}
    versionFunctions: false # ${env:VERSION_FUNCTIONS, 'false'}
    endpointType: ${env:ENDPOINT_TYPE, 'Edge'}
    tracing:
      apiGateway: false # ${env:TRACING_API_GATEWAY, 'true'}
      lambda: true # ${env:TRACING_LAMBDA, 'true'}
    logs:
      restApi:
        accessLogging: true # ${env:LOGS_ACCESS_LOGGING, 'true'}
        executionLogging: true # ${env:LOGS_EXECUTION_LOGGING, 'true'}
        level: ${env:LOGS_LEVEL, 'INFO'}
        fullExecutionData: true # ${env:LOGS_FULL_EXECUTION_DATA, 'true'}
      websocket: true # ${env:LOGS_WEBSOCKET, 'true'}
      frameworkLambda: true # ${env:LOGS_FRAMEWORK_LAMBDA, 'true'}

  namePrefix: ${self:provider.stage}-${self:provider.region}
  fullstack_config:
    qa:
      domain: staging.example.io
      certificate: ''
      bucketName: serverless-${self:custom.namePrefix}-frontend
      clientCommand: npm install && ng build --configuration qa
    prod:
      domain: example.io
      certificate: ''
      bucketName: serverless-${self:custom.namePrefix}-frontend
      clientCommand: npm install && ng build --aot --prod

  fullstack:
    distributionFolder: webapp/dist/webapp
    singlePageApp: true
    clientCommand: ${self:custom.fullstack_config.${self:provider.stage}.clientCommand
    clientSrcPath: webapp
```
This gives error while creating bucket

https://ibb.co/h7RtDtM

```
Bucket name should not contain uppercase characters
```

Passing the `bucketName` manually gives the following error
```

Serverless Error ---------------------------------------
 
  ServerlessError: Client generation failed with code 2
      at ChildProcess.proc.on (/opt/atlassian/pipelines/agent/build/node_modules/fullstack-serverless/index.js:146:24)
      at ChildProcess.emit (events.js:198:13)
      at ChildProcess.EventEmitter.emit (domain.js:448:20)
      at maybeClose (internal/child_process.js:982:16)
      at Socket.stream.socket.on (internal/child_process.js:389:11)
      at Socket.emit (events.js:198:13)
      at Socket.EventEmitter.emit (domain.js:448:20)
      at Pipe._handle.close (net.js:606:12)
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:489:22)
      at getHooks.reduce.then (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:524:24)
  From previous event:
      at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:524:8)
      at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:115:33)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:102:74)
      at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless.js:72:30)
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
      at FSReqWrap.args [as oncomplete] (fs.js:140:20)
  From previous event:
      at initializeErrorReporter.then (/usr/local/lib/node_modules/serverless/bin/serverless.js:72:8)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:61:4)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
      at startup (internal/bootstrap/node.js:283:19)
      at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by hakimio** [comment]
Maybe instead of `qa` it should be `dev`? Is your stage environmental variable set correcty? Do you use any other plugins?

**Comment by anuj9196** [comment]
Yes, it is `qa` and all other functions are deployed successfully under `qa` stage.
I have only two plugins installed
```
serverless-offline
fullstack-serverless
```

**Comment by hakimio** [comment]
Do you put valid certificate arn or do you leave it as blank string? Can you share your `cloudformation-template-create-stack.json` and `cloudformation-template-update-stack.json` files?

**Comment by anuj9196** [comment]
As you can see in the configs above, I have not passed any certificate arn.
Here are the requested files:

1. [cloudformation-template-create-stack.json](https://gist.github.com/anuj9196/0f8b7f725237294ad971e08781820b6a)
2. [cloudformation-template-update-stack.json](https://gist.github.com/anuj9196/a63a599cfaa9b5f826b96777db28771d)

**Comment by hakimio** [comment]
You shouldn't set any configs to empty strings if you want to leave them in default state. The script will try to configure the certificate if it's not null or undefined: [index.js#L400](https://github.com/MadSkills-io/fullstack-serverless/blob/master/index.js#L400)

**Comment by anuj9196** [comment]
@hakimio But I have nothing set to empty string. If you are talking about `fullstack_config` attribute, it is there just to store the values per stage which can be used in `fullstack` attributes.

As per the documentation, the plugin will look for `fullstack` variable inside `custom` and no certificate has been defined there.

**Comment by hakimio** [comment]
Ok, I can see that now.
Another thing I noticed. Following seems to be missing a closing brace:
`clientCommand: ${self:custom.fullstack_config.${self:provider.stage}.clientCommand`

**Comment by anuj9196** [comment]
@hakimio Thanks, it's solved now. But after deploying, opening the CloudFront URL [d14n5nuglmw5o4.cloudfront.net](d14n5nuglmw5o4.cloudfront.net) gives AccessDenied error.

**Comment by hakimio** [comment]
@anuj9196 Yeah, that's a CloudFront issue. Normally waiting few hours fixes it. [StackOverflow thread](https://stackoverflow.com/questions/42251745/aws-cloudfront-access-denied-to-s3-bucket/42285049).
If it doesn't, open your distribution in CloudFront Console, go to "Origins",  edit "WebApp" origin, select "Yes, update bucket policy" and save it.

**Comment by anuj9196** [comment]
@hakimio Thanks for the help. You are great. It's working now.
What is the usage of the `apiPath`? As per the documentation, 

> The path prefix for your API Gateway lambdas. The path for the lambda HTTP event trigger needs to start with this too eg. api/myMethod 

My API endpoint (nodejs application) is running on `<cloudflare_url>.com/qa/myMethod`
So, probably the `apiPath` will be set to `qa`. (If, I'm not wrong!)

But how can I access that `apiPath` from my **Angular** application?

**Comment by hakimio** [comment]
If you are using API Gateway AWS service for your backend, you can specify the path of your API endpoint to be let's say `api`:
```yml
functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          path: api
          method: any
```
If you do that, `fullstack-serverless` plugin can configure CloudFront distribution origin and behavior, so that you don't need to use CORS to access your backend. You'll be able to just call the backend using frontend domain, something like `https://myfrontend.com/api`.

It's a nice feature but not a must have and you can also configure it manually yourself.

**Comment by anuj9196** [comment]
@hakimio This is my updated `fullstack` configuration
```
fullstack:
    bucketName: serverless-${self:custom.namePrefix}-frontend
    distributionFolder: webapp/dist/webapp
    singlePageApp: true
    clientCommand: ${self:custom.fullstack_config.${self:provider.stage}.clientCommand}
    clientSrcPath: webapp
    apiPath: qa

functions:
  scanProcessor:
    handler: handler.server
    events:
      - http:
          path: /
          method: ANY
          cors: true

      - http:
          path: /{proxy+}
          method: ANY
          cors: true
```
The API url by cloudflare is
```
https://qxlnbnph0f.execute-api.ap-south-1.amazonaws.com/qa/check
```
I'm making request to the above URL through Angular service.
It gives `200` response, but no data is returned. Also request status in Angular gives `0`.

### Headers
```
General
------------
Request URL: https://qxlnbnph0f.execute-api.ap-south-1.amazonaws.com/qa/check
Request Method: POST
Status Code: 200 
Remote Address: 13.227.143.4:443
Referrer Policy: no-referrer-when-downgrade

Response Header
-------------------------
content-length: 282
content-type: application/json; charset=utf-8
date: Fri, 01 Nov 2019 09:19:01 GMT
etag: W/"11a-xTObt9pL8aH9nyOf0gR8mn7UrJM"
status: 200
strict-transport-security: max-age=15552000; includeSubDomains
via: 1.1 49a7052b1cf6cbcdc134f38b7efabee5.cloudfront.net (CloudFront)
x-amz-apigw-id: CePEoG_DhcwFQTA=
x-amz-cf-id: TgKYW5obC3JcLHkeXkanVO266tKGQKCfve_aUBYnzGvy8cCiXtkrJA==
x-amz-cf-pop: BOM50-C1
x-amzn-remapped-content-length: 282
x-amzn-requestid: b25c9c11-9000-4bb3-8bde-3b73c10bd3f4
x-amzn-trace-id: Root=1-5dbbf883-70db2442d48e002ef1b8018c;Sampled=1
x-cache: Miss from cloudfront
x-content-type-options: nosniff
x-dns-prefetch-control: off
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block

Request Headers
--------------------------
Accept: application/json, text/plain, */*
Authorization: Hash
Content-Type: application/json
DNT: 1
Origin: https://d14n5nuglmw5o4.cloudfront.net
Referer: https://d14n5nuglmw5o4.cloudfront.net/BzjK
Sec-Fetch-Mode: cors
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
```

What could be the issue?
