### ISSUE TITLE
Nothing is deployed

### ISSUE THREAD

**Issue by clarkd** [MadSkills-io/fullstack-serverless#21]
I'm not sure what I'm missing here. I've setup a basic app with create-react-app and trying to deploy it. Here is my serverless.yml:

```
service: my-app

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev #default

  plugins:
    - fullstack-serverless
  
  custom:
    fullstack:
      domain: app.mydomain.com
      certificate: 	arn:aws:acm:us-east-xxxxxxxxxx     
      bucketName: client 
      distributionFolder: build             
      indexDocument: index.html                 
      errorDocument: error.html                  
      singlePageApp: true                        
      compressWebContent: true                  
      clientCommand: npm run-script build       
```

This is the output I get, the command finishes in around 5-10 seconds. A bucket exists in AWS but it only contains the serverless folder and not my site.

```
PS C:\Users\dave.clarke\Documents\Code Repository\saas\client> serverless deploy
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Updating Stack...
Service Information
service: xxxxxxxxx
stage: dev
region: us-east-1
stack: xxxxxxxxxx
resources: 2
api keys:
  None
endpoints:
  None
functions:
  None
layers:
  None
Serverless: Run the "serverless" command to setup monitoring, troubleshooting and testing.
```

Any ideas - not sure what I'm missing?
