### ISSUE TITLE
service name gets prepended to the bucketName

### ISSUE THREAD

**Issue by saadtazi** [MadSkills-io/fullstack-serverless#27]
Hello,
With the following configuration:

```
service: my-webapp

plugins:
  - fullstack-serverless

provider:
  name: aws
  versionFunctions: false
  region: ${opt:region, 'us-east-1'}
  stage: dev # default stage

custom:
  stage: "${opt:stage, self:provider.stage}"
  profiles:
    dev: dev-profile
  fullstack:
    bucketName: my-webapp-dev
    distributionFolder: build
    indexDocument: index.html
    errorDocument: error.html
    singlePageApp: true
    # clientCommand: npm run builddoing nothing
    # clientSrcPath: client

```

i get the following error:

```
sls client deploy --no-confirm --stage dev
Serverless: Skipping client generation...
Serverless: This deployment will:
Serverless: - Remove all existing files from bucket 'my-webapp-dev-my-webapp-saad'
Serverless: - Upload all files from 'build' to bucket 'my-webapp-dev-my-webapp-saad'
Serverless: Looking for bucket 'my-webapp-dev-my-webapp-saad'...
Serverless: Bucket does not exist. Run serverless deploy

  Serverless Error ---------------------------------------

  Bucket does not exist!

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              13.8.0
     Framework Version:         1.67.3
     Plugin Version:            3.6.6
     SDK Version:               2.3.0
     Components Version:        2.29.1

```
Notice that the bucket name in the logs is `my-webapp-dev-my-webapp-saad`, not just `my-webapp-saad`.

Is there a way to not prepend the service name to the bucketName?
