### ISSUE TITLE
Files are not public inside the S3 bucket

### ISSUE THREAD

**Issue by b-vetter** [MadSkills-io/fullstack-serverless#28]
I use currently the following serverless configuration for my small react application.

```
service: my-service-name

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

plugins:
  - fullstack-serverless

custom:
  fullstack:
    bucketName: my-bucket-name                  # Unique name for the S3 bucket to host the client assets 
    distributionFolder: ./build            # Path to the client assets to be uploaded to S3 
    indexDocument: index.html                  # The index document to use 
    errorDocument: index.html                  # The error document to use 
    singlePageApp: true                       # If true 403 errors will be rerouted (missing assets) to your root index document to support single page apps like React and Angular where the js framework handles routing 
    compressWebContent: true                   # Use compression when serving web content 
    noConfirm: false                           # Alternative to --no-confirm flag. Use this parameter if you do not want a confirmation prompt to interrupt automated builds.
```

The fullstack plugin works fine but I've a problem.
The files inside the created S3 bucket are not automatically public so that I must manually change the permission of the files to public.
That means that I get after the deployment just an AccessDenied error from the website.

Can I configure that or can you add an option to set the permission automatically?
