### ISSUE TITLE
Custom variables break plugin

### ISSUE THREAD

**Issue by jeremygottfried** [MadSkills-io/fullstack-serverless#31]
This works:
```yml
fullstack: 
  domain: mydomain.com
  certificate: xxxxxxxxxxxxxxx
  distributionFolder: ../web/build
  apiPath: api
  clientCommand: yarn run build
  clientSrcPath: ../web/
  bucketName: mybucketname
  singlePageApp: true
  noConfirm: true
```

This breaks (with exactly the same config):
```yml
stage: "${opt:stage, self:provider.stage}"
fullstack: ${file(./fullstack.${self:custom.stage}.yml)}
```

```sh
  Fullstack serverless configuration errors:
  - Could not find '/Users/xxx/xxx/xxx/client/dist' folder in your project root
  - Please specify a bucket name for the client in serverless.yml
```
