### ISSUE TITLE
Staging/Dev environment

### ISSUE THREAD

**Issue by davej** [MadSkills-io/fullstack-serverless#5]
Is there any concept of staging/dev with this plug-in? Any thoughts on how to do this?

**Comment by superandrew213** [comment]
You can just deploy using your serverless dev or prod profile. This would create 2 different deployments and 2 different urls.

You could also just adjust the `domain` and `certificate` settings.

If it is not a toy project, I would also use separate AWS accounts for dev/staging/prod.

**Comment by andrewphahn** [comment]
@superandrew213 is right, the plugin respects the stage from serverless when deploying the CloudFront distro and S3 bucket such that the name is different for each stage.

To have different values for each stage in the `serverless.yaml` file here is what I do  
_Note that `dev` and `production` are the names of the stages from serverless_
```yaml
custom:
  # The current stage value
  stage: "${opt:stage, self:provider.stage}"

  # Stage specific variable base
  stage_specific: ${self:custom.${self:custom.stage}}

  # Values for the dev stage
  dev:
    customDomain:
      domainName: "dev.example.com"
      certificate: arn:aws:acm:...1234

  # Values for the production stage
  production:
    customDomain:
      domainName: "prod.example.com"
      certificate: arn:aws:acm:...5678

  # Stage dependent config
  fullstack:
    domain: ${self:custom.stage_specific.customDomain.domainName}
    certificate: ${self:custom.stage_specific.customDomain.certificate}
```

To use two different accounts for dev and prod (I recommend doing it) you can do the same thing with the AWS profile as well

```yaml
provider:
  name: aws
  profile: ${self:custom.stage_specific.profile}
```
